```{r setup-section-ggplot, echo=FALSE, include=FALSE}
bikes <- readr::read_csv("https://www.cedricscherer.com/data/london-bikes.csv", col_types = "Dcfffilllddddfc")
```

# The {ggplot2} Package {#ggplot}

<p class="comment">

ADD SHORT HISTORY OF GGPLOT2

</p>

When looking into the package description of the **{ggplot2}** package, it states the following:

> **{ggplot2}** is a system for declaratively creating graphics, based on [The Grammar of Graphics](https://link.springer.com/chapter/10.1007/978-3-642-21551-3_13). You provide the data, tell **{ggplot2}** how to map variables to aesthetics, what graphical primitives to use, and it takes care of the details.

The most important insight from that technical description is that (1) it relies on a framework called the grammar of graphics (hence the gg in **{ggplot2}**) and (2) we map variables to aesthetics. This is an important concept when writing **{ggplot2}** code.

## The Structure of a ggplot

In general, a ggplot is built up from the following components:

1.  **Data**:\
    The raw data that you want to plot.
2.  **Aesthetics** `aes()`:\
    The mapping of variables to visual properties, such as position, color, size, shape, and transparency.
3.  **Layers:**\
    The representation of the data on the plot panel which is a combination of the  geometric shapes (`geom_`) representing the data and the statistical transformation ( \`stat\_\`) of the data, such as fitted curves, counts, and data summaries.
4.  **Scales** `scale_`:\
    The control of the mapping between the data and the aesthetic dimensions, such as data range to positional aesthetics or qualitative or quantitative values to colors.
5.  **Coordinate system** `coord_`:\
    The transformation used for mapping data coordinates into the plane of the graphic.
6.  **Facets** `facet_`:\
    The arrangement of the data into a grid of plots (also known as *trellis* or *lattice plot*, or simply *small multiples*).
7.  **Visual themes** `theme()`:\
    The overall visual (non-data) details of a plot, such as background, grid lines, axes, typefaces, sizes, and colors.

<p class="note">

The number of elements may vary depending on how you group them and whom you ask. This list is based on the list provided in the ["ggplot2" book by Hadley Wickham](https://ggplot2-book.org/introduction.html).

</p>

A basic ggplot needs three things that you have to specify: the *data*, *aesthetics*, and a *layer*. All other components can be further combined and modified to customize your chart.

You can think of a ggplot as a receipt for a dish: it can be based on a few or a diversity of ingredients. Also, you are free to add additional ingredients to spice-up your creation (literally and visually). 

Similarly, you can build rather basic charts such as scatter plots or histograms with only a few lines code. But `{ggplot2}` also allows to create rather complex charts that combine multiple geometries, statistical transformations and maybe even data sets. On top, it is up to you how much effort you take to polish the plot. You can rely on the defaults used for data-related aesthetics (e.g. default axis breaks and color palettes) and non-data aspects (e.g. complete themes). Or you decide to modify the data-related aesthetics such as axes and color palettes and/or customize the theme elements of your graphic to your needs. 


### Data

No data visualization without data. 







