```{r 97setupSectionGraveyard, echo=FALSE, include=FALSE, freeze=FALSE}
source(here::here("src", "prerequisites.R"))
```

```{r, echo=FALSE, fig.width=8, fig.height=4}
p1 <- 
  ggplot(bikes, aes(x = date, y = count)) +
  layer(geom = "point", stat = "identity", position = "identity")

p2 <- 
  ggplot(bikes, aes(x = temp)) +
  layer(geom = "bar", stat = "bin", position = "identity")

p3 <- 
  ggplot(bikes, aes(x = wind_speed, y = humidity)) +
  layer(geom = "smooth", stat = "smooth", position = "identity", params = list(se = TRUE))

p1 + plot_spacer() + p2 + plot_spacer() + p3 + 
  plot_layout(nrow = 1, widths = c(1, .03, 1, .03, 1))
```

*************

For example, `geom_histogram()` or `stat_bin()` both create histograms representing the distribution of a continuous variable as binned bars:

```{r, eval=FALSE}
ggplot(bikes, aes(x = temp)) + geom_histogram() 
ggplot(bikes, aes(x = temp)) + stat_bin()
```

Both functions call the same `layer()` function with the predefined defaults `geom = "bar"`, `stat = "bin"`, and `position = "identity"`.

*************

```{r, eval=FALSE, include=FALSE}
theme_set(theme_void(base_family = "Spline Sans Mono")) 
theme_update(
  panel.background = element_rect(fill = "grey96", color = "grey10"),
  plot.title = element_text(face = "bold", hjust = .5, margin = margin(10, 0, 10, 0)),
  legend.position = "none"
)


library(dplyr)
bikes_month <- bikes %>% group_by(month) %>% summarize(count = sum(count)) %>% arrange(count)
bikes_season <- bikes %>% group_by(season) %>% summarize(avg = mean(temp), lwr = mean(temp) - sd(temp), upr = mean(temp) + sd(temp))

c1r <- ggplot(bikes, aes(x = temp)) + geom_blank()
c2r <- ggplot(bikes, aes(x = temp, y = humidity)) + geom_blank() + 
  scale_fill_gradient(low = "grey85", high = "grey28")
c2s <- ggplot(bikes_month, aes(x = as.numeric(month), y = count)) + geom_blank()
cd1r <- ggplot(bikes, aes(x = weather_type)) + geom_blank()
cd2r <- ggplot(bikes, aes(x = season, y = temp)) + geom_blank()
cd2s <- ggplot(bikes_season, aes(x = season, y = avg, ymin = lwr, ymax = upr)) + geom_blank()

fd <- ggplot(faithfuld, aes(x = waiting, y = eruptions, z = density)) + coord_cartesian(expand = FALSE) + 
  scale_fill_manual(values = grey.colors(n = 8, start = .1, end = .96, rev = TRUE))
fs <- ggplot(faithful, aes(x = waiting, y = eruptions)) + coord_cartesian(expand = FALSE) + 
  scale_fill_manual(values = grey.colors(n = 13, start = .1, end = .96, rev = TRUE))


abline <- c2s + geom_abline(slope = 1000, intercept = 5000) + ggtitle("geom_abline()")
hline <- c2s + geom_hline(yintercept = 1700000) + ggtitle("geom_hline()")
vline <- c2s + geom_vline(xintercept = 6.5) + ggtitle("geom_vline()")

blank <- c2r + ggtitle("geom_blank()")

# 2d 
area <- c2s + geom_area() + ggtitle("geom_area()")


# 1d distributions
boxplot <- cd2r + geom_boxplot() + ggtitle("geom_boxplot()")

# 1d counts
bar <- cd1r + geom_bar() + ggtitle("geom_bar()")
col <- cd2s + geom_col() + ggtitle("geom_col()")


## 2d density
bin_2d <- c2r + geom_bin_2d(bins = 15) + ggtitle("geom_bin_2d()")

contour <- fd + geom_contour(color = "black") + ggtitle("geom_contour()")
contour_filled <- fd + geom_contour_filled() + ggtitle("geom_contour_filled()")

density_2d <- c2r + geom_density_2d(color = "black") + ggtitle("geom_density_2d()")
density_2d <- fs + geom_density_2d(color = "black") + ggtitle("geom_density_2d()")
density_2d_filled <- fs + geom_density_2d_filled() + ggtitle("geom_density_2d_filled()")


point

count <- ggplot(bikes, aes(y = interaction(season, year), x = count %% 10)) + geom_count() + ggtitle("geom_count()")
set.seed(1)
count <- ggplot(tibble(x = round(rnorm(n = 500, sd = .2), 1), y = round(rnorm(n = 500, sd = .2), 1)), aes(x = x, y = y)) + geom_count() + ggtitle("geom_count()")

crossbar <- cd2s + geom_crossbar() + ggtitle("geom_crossbar()")
#geom_curve()
#geom_dotplot(size = .3)
errorbar <- cd2s + geom_errorbar() + ggtitle("geom_errorbar()")
errorbarh <- ggplot(bikes_season, aes(y = season, xmin = lwr, xmax = upr)) + geom_errorbarh() + ggtitle("geom_errorbar()")
#geom_freqpoly()
#geom_function()
hex <- c2r + geom_hex(bins = 15) + ggtitle("geom_hex()")
histogram <- c1r + geom_histogram() + ggtitle("geom_histogram()")
jitter <- cd2r + geom_jitter() + ggtitle("geom_jitter()")
label <- cd2s + geom_label(aes(label = round(avg, 1)), family = "Asap Condensed")  + ggtitle("geom_label()")
text <- cd2s + geom_text(aes(label = round(avg, 1)), family = "Asap Condensed")  + ggtitle("geom_text()")
line <- c2s + geom_line() + ggtitle("geom_line()")
linerange <- cd2s + geom_linerange() + ggtitle("geom_linerange()")
#geom_map()
path <- c2s + geom_path() + ggtitle("geom_path()")
point <- c2r + geom_point() + ggtitle("geom_point()")
pointrange <- cd2s + geom_pointrange() + ggtitle("geom_pointrange()")
#geom_polygon()
qq <- ggplot(bikes) + geom_qq(aes(sample = temp)) + ggtitle("geom_qq()")
qq_line <- ggplot(bikes) + geom_qq_line(aes(sample = temp)) + ggtitle("geom_qq_line()")
quantile <- c2r + geom_quantile(color = "black") + ggtitle("geom_quantile()")
#geom_raster()
#geom_rect()
#geom_ribbon()
c2r + geom_rug(alpha = .3)
#geom_segment()
#geom_sf()
#geom_sf_label()
#geom_sf_text()
smooth <- c2r + geom_smooth(color = "black") + ggtitle("geom_smooth()")
#geom_spoke()
step <- c2s + geom_step() + ggtitle("geom_step()")
#geom_tile()
violin <- cd2r + geom_violin() + ggtitle("geom_step()")
```
